# Generated by Django 3.0.8 on 2020-07-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pubDate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('tag', models.CharField(choices=[(1, 'Travelling'), (2, 'Food'), (3, 'Technology'), (4, 'Information')], default=None, max_length=20)),
                ('feature', models.CharField(choices=[(1, 'Hot Rated'), (2, 'Most Viewed')], default=None, max_length=20)),
                ('blog', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=50)),
                ('bg_img', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
