# Generated by Django 3.0.8 on 2020-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogView', '0002_auto_20200724_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='feature',
            field=models.CharField(choices=[('1', 'Hot Rated'), ('2', 'Most Viewed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('1', 'Travelling'), ('2', 'Food'), ('3', 'Technology'), ('4', 'Information')], max_length=20),
        ),
    ]
