# Generated by Django 3.0.8 on 2020-07-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogView', '0003_auto_20200724_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.CharField(max_length=5000),
        ),
    ]
