# Generated by Django 3.0.8 on 2020-07-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogView', '0004_auto_20200724_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.CharField(max_length=100)),
                ('bg_img', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
