# Generated by Django 3.0.8 on 2020-07-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogView', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pubDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='bg_img',
            field=models.ImageField(upload_to='uploads/video'),
        ),
    ]
