# Generated by Django 3.0.8 on 2020-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogView', '0006_auto_20200724_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bg_img',
            field=models.ImageField(upload_to='uploads/blog'),
        ),
    ]
