# Generated by Django 3.0.8 on 2020-07-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogView', '0007_auto_20200724_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
