# Generated by Django 3.0.8 on 2020-07-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogView', '0011_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
