# Generated by Django 3.0 on 2020-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogView', '0013_auto_20201001_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.BooleanField(default=False),
        ),
    ]
