# Generated by Django 3.0 on 2020-10-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogView', '0014_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.TextField(max_length=5000),
        ),
    ]
